[project]
name = "titan-forge"
version = "0.1.0"
description = "Add a short description here"
authors = ["Ethan C"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]

[dependencies]
python = ">=3.13.1,<3.14"
opencv = { path = ".output/linux-64/opencv-titan-4.10.0-h90f2c7a_1.conda"}
pygobject = "*"

[pypi-dependencies]
ipython = "*"
viztracer = ">=1.0.0, <2"
