context:
  name: librealsense
  version: 2.55.1
  

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  - url: https://github.com/IntelRealSense/librealsense/archive/v${{ version }}.tar.gz
    sha256: 54546d834ff5d8b35d9955319ad2e428f6d9ae4c61b932d1bd716ed81ad135f7

build:
  script: build-librealsense.sh

requirements:
  build:
    - python
    - if: build_platform != target_platform
      then: cross-python_${{ target_platform }}
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - cmake
    - ninja
    - libudev
    - ${{ stdlib('c') }}
  host:
    - python
    - numpy
    - libudev
    - libusb
  run:
    - ${{ pin_compatible('numpy') }}

# tests:
#   - python:
#       imports:
#         - pyrealsense2

about:
  homepage: https://github.com/IntelRealSense/librealsense
  license: Apache-2.0
  license_file: LICENSE
  summary: Cross-platform library for Intel® RealSense™ depth and tracking cameras.

extra:
  recipe-maintainers:
    - ethanc8
